content_location: ./content
base_url: https://example.com
flavours:
  - name: any_language
    includes:
      - javascript
      - python
      - java
      - kotlin
      - swift
      - typescript
      - bash

  # any_unit_testing:
  #   - pytest
  #   - junit
  #   - jasmine

  # any_frontend_framework:
  #   - react
  #   - angular
  #   - noframework

  # any_mobile_development_toolset:
  #   - ionic

  # none:
  #   - none

  # any_fullstack_web_framework:
  #   - django

  # any_plain_text:
  #   - markdown

  # misc:
  #   - redux

  # databases:
  #   - postgres
  #   - mongo
